name: up4
description: up4

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  rxdart: ^0.19.0
  fluro: ^1.3.5

  cloud_firestore: ^0.8.1
  firebase_auth: ^0.6.2
  firebase_messaging: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
